name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    services:
      entregas:
        image: api-entregas-image
        ports:
          - 8080:8080
        options: >-
          --health-cmd="curl --fail http://localhost:8080/actuator/health || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Wait for ms-entregas to be ready
        run: |
          echo " Aguardando o serviço ms-entregas subir..."
          for i in {1..30}; do
            curl -s http://localhost:8080/actuator/health && break
            sleep 2
          done

      - name: Run tests
        run: mvn clean test

  deploy:
    runs-on: ubuntu-latest
    needs: continuous-integration
    if: success()
    steps:
      - name: Deploy application
        run: echo "Deploying application..."
